import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import DynamicBackground from '@/components/dynamic-background/dynamic-background'
import Header from '@/components/header/header'
import TextImageSection from '@/components/text-image/text-image'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
	return (
		<>
			<Head>
				<title>UPDATE THIS + FAVICON</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main>
				<DynamicBackground />
				<Header />
				<TextImageSection />
			</main>
		</>
	)
}
